config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  root to: 'home#index'

  resources :users do
    resources :products
  end

  resources :products do
    resources :comments
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :name, :description, :price, :presence => true
  validates :price, numericality: { only_integer: true }
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :only => [:new]

  before_action :only => [:edit] do
    redirect_to '/' unless is_admin? || is_current_user?
  end
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @product = @user.products.new
  end

  def create
    @user = User.find(params[:user_id])
    @product = @user.products.new(product_params)
    if @product.save
      redirect_to user_path(@product.user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @product = Product.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to user_path(@product.user)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to user_path(@product.user)
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/views/products/_form.html.erb
<%= render 'layouts/errors', :object => @product %>

<%= form_for [@user, @product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <p><%= f.submit %></p>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= render 'form'%>

app/views/products/index.html.erb
``<%if user_signed_in?  %>
<h1>All Photos on Display</h1>
<% @products.each do |product| %>

  <br>
  <div class="polaroid">
    <%= image_tag product.image %>
    <div class="myContent">
        <%= link_to "View details page", product_path(product) %>
      <br>
      Name: <%= product.name %>
      <br>
      Description: <%= product.description %>
      <br>
      Price: <%= product.price %>
    </div>
  </div>

  <% if is_admin?  %>


    <%= link_to "Edit Product", edit_product_path(product) %> |
    <%= link_to "Delete this Product", product_path(product),
            :data => {:confirm => "Are you sure?",
              :method => "delete"} %>

    <% end %>


  <hr>

<% end %>
<% else %>

<h1> Please Sign Up or Login to view images</h1>
<% end %>

app/views/products/new.html.erb
<h2>New Product added by: <%= @user.username %></h2>

<%= render 'form'%>

app/views/products/show.html.erb
<div class="container">
  <h1> Specific Product Page</h1>


  <div class="row">
   <div class="col-lg-8">

     <br>
     <div class="polaroid">
       <%= image_tag @product.image %>
       <div class="myContent">
         Name: <%= @product.name%>
         <br>
         Description: <%= @product.description%>
         <br>
         Price: <%= @product.price%>
       </div>
     </div>
     <hr>
   </div>
   <div class="col-lg-4">
       <%= link_to "Add Comment", new_product_comment_path(@product) %>
     <% if @product.comments.any? %>
     <h3>Comments:</h3>
       <% @product.comments.each do |comment| %>
         Title: <%= comment.title %>
         <br>
         Written by: <%= comment.author %>
         <br>
         Content: <%= comment.content %>
         <br>

         <% if is_admin? %>
           <%= link_to "Edit Comment", edit_product_comment_path(@product, comment) %> |
           <%= link_to "Delete this comment", product_comment_path(@product, comment),
                   :data => {:confirm => "Are you sure?",
                     :method => "delete"} %>

           <% end %>

       <br>
       <hr>
       <% end %>
     <% else %>
     <p>There are no comments yet!</p>
     <% end %>
   </div>
  </div>
</div>


<br>

<br>