config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  root to: 'home#index'

  resources :users do
    resources :products
  end

  resources :products do
    resources :comments
  end

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MilesOfSmiles</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Home', '/', {class: "navbar-brand"} %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "View All Photo Packages", products_path %></li>
          <li><%= link_to current_user.email, user_path(current_user) %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to "View All Photo Packages", products_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
   <div class="container">
     <%= render 'layouts/messages' %>
     <%= yield %>
   </div>
  </body>
</html>